name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate the snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lhlizdabezt
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-tokyonight.svg?palette=github-dark&color_snake=#2563eb&color_dots=#0f172a,#0f766e,#2563eb,#8e44ad,#d95319

      - name: Push generated svgs to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
